# Generated by Django 5.2.16 on 2026-08-26 23:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0166_item_source_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectionField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("number", "Number"),
                            ("date", "Date"),
                            ("select", "Select"),
                            ("checkbox", "Checkbox"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Selectable choices, only used when field_type is 'select'",
                    ),
                ),
                (
                    "media_types",
                    models.JSONField(
                        default=list,
                        help_text="MediaTypes values this field applies to",
                    ),
                ),
                ("position", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="CollectionFieldGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("position", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.AddField(
            model_name="collectionentry",
            name="custom_field_values",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Values for user-defined CollectionField entries, keyed by field id",
            ),
        ),
        migrations.AddField(
            model_name="collectionfieldgroup",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collection_field_groups",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="collectionfield",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fields",
                to="app.collectionfieldgroup",
            ),
        ),
        migrations.AddIndex(
            model_name="collectionfieldgroup",
            index=models.Index(
                fields=["user", "position"], name="app_collect_user_id_3ebb2e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="collectionfield",
            index=models.Index(
                fields=["group", "position"], name="app_collect_group_i_09b351_idx"
            ),
        ),
    ]
