# Generated by Django 5.2.16 on 2026-08-31 21:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0171_fix_year_one_release_datetime"),
        ("app", "0171_report_duplicated_anime_libraries"),
    ]

    operations = []
