# Generated by Django 5.2.16 on 2026-09-03 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0173_alter_item_source_add_plex"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metadatabackfillstate",
            name="field",
            field=models.CharField(
                choices=[
                    ("runtime", "Runtime"),
                    ("genres", "Genres"),
                    ("credits", "Credits"),
                    ("release", "Release Date"),
                    ("discover", "Discover Metadata"),
                    ("game_lengths", "Game Lengths"),
                    ("trakt_popularity", "Trakt Popularity"),
                    ("igdb_ratings", "IGDB Ratings"),
                    ("watch_providers", "Watch Providers"),
                    ("external_ids", "External IDs"),
                ],
                max_length=20,
            ),
        ),
    ]
