# Generated by Django 5.2.16 on 2026-09-08 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0168_sync_provider_choices'),
        ('app', '0178_watchstate_watchstatechange_watchstatesequence'),
    ]

    operations = [
    ]
