# Generated by Django 5.2.17 on 2026-10-07 18:16

import app.models.media
import django.core.serializers.json
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models
from django.db.models import OuterRef, Subquery

from importlib import import_module

_constraint_operations = import_module("integrations.migrations.0030_radarrinstance_sonarrinstance_and_more")
_index_operations = import_module("app.migrations.0134_item_app_item_media_lookup_idx")
AddFieldIfNotExists = _constraint_operations.AddFieldIfNotExists
AddConstraintIfNotExists = _constraint_operations.AddConstraintIfNotExists
RemoveConstraintIfExists = _constraint_operations.RemoveConstraintIfExists
AddIndexIfNotExists = _index_operations.AddIndexIfNotExists


def backfill_episode_history_status(apps, schema_editor):
    """Recover dropped and unfinished historical plays from preserved state."""
    episode_model = apps.get_model("app", "Episode")
    history_model = apps.get_model("app", "HistoricalEpisode")
    alias = schema_editor.connection.alias
    history = history_model.objects.using(alias)
    history.filter(dropped=True).update(status="Dropped")
    open_plays = episode_model.objects.using(alias).exclude(status__in=["Completed", "Dropped"])
    history.filter(id__in=open_plays.values("id"), end_date__isnull=True, dropped=False).update(
        status=Subquery(open_plays.filter(id=OuterRef("id")).values("status")[:1]),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0181_public_branding'),
        ('integrations', '0037_merge_20260908_1855'),
        ('users', '0151_branding_presentation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EpisodeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=20)),
                ('series_id', models.CharField(max_length=500)),
                ('key', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('catalogue', models.JSONField(default=dict)),
                ('revision', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='EpisodeOrderChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mappings', models.JSONField(default=list)),
                ('before_state', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalVideo',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.DecimalValidator(3, 1), django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('progress', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(blank=True, choices=[('Completed', 'Completed'), ('In progress', 'In Progress'), ('Planning', 'Planning'), ('Paused', 'Paused'), ('Dropped', 'Dropped')], default='Completed', max_length=20, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('entry_source', models.CharField(blank=True, default='', max_length=50)),
                ('channel', models.CharField(blank=True, default='', max_length=255)),
                ('watch_url', models.URLField(blank=True, default='', max_length=500)),
                ('length_seconds', models.PositiveIntegerField(default=0)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical video',
                'verbose_name_plural': 'historical videos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ProgressChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.BigIntegerField()),
                ('kind', models.CharField(choices=[('upsert', 'Upsert'), ('delete', 'Delete')], default='upsert', max_length=8)),
                ('position_seconds', models.PositiveIntegerField(default=0)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('origin_key', models.CharField(blank=True, default='', max_length=128)),
                ('correlation_id', models.UUIDField(default=uuid.uuid4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Progress change',
                'verbose_name_plural': 'Progress changes',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='StatisticsDirtyDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('token', models.UUIDField(default=uuid.uuid4)),
                ('marked_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='StatisticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range_name', models.CharField(max_length=32)),
                ('payload', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('generation', models.BigIntegerField(default=0)),
                ('built_day', models.DateField()),
                ('built_at', models.DateTimeField()),
                ('schema_version', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StatisticsSyncState',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='+', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('generation', models.BigIntegerField(default=1)),
                ('hot_synced_generation', models.BigIntegerField(default=0)),
                ('heavy_synced_generation', models.BigIntegerField(default=0)),
                ('heavy_synced_at', models.DateTimeField(blank=True, null=True)),
                ('synced_day', models.DateField(blank=True, null=True)),
                ('last_marked_at', models.DateTimeField(blank=True, null=True)),
                ('full_sweep_requested_at', models.DateTimeField(blank=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('lease_token', models.UUIDField(blank=True, null=True)),
                ('last_started_at', models.DateTimeField(blank=True, null=True)),
                ('last_finished_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.DecimalValidator(3, 1), django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('scored_at', app.models.media.ScoreMonitorField(blank=True, default=None, monitor='score', null=True)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('progressed_at', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='progress')),
                ('status', models.CharField(blank=True, choices=[('Completed', 'Completed'), ('In progress', 'In Progress'), ('Planning', 'Planning'), ('Paused', 'Paused'), ('Dropped', 'Dropped')], default='Completed', max_length=20, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('entry_source', models.CharField(blank=True, default='', max_length=50)),
                ('channel', models.CharField(blank=True, default='', max_length=255)),
                ('watch_url', models.URLField(blank=True, default='', max_length=500)),
                ('length_seconds', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='VideoPlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('external_id', models.CharField(max_length=255)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('end_date', models.DateTimeField()),
            ],
        ),
        RemoveConstraintIfExists(
            model_name='item',
            name='app_item_media_type_valid',
        ),
        RemoveConstraintIfExists(
            model_name='item',
            name='app_item_library_media_type_valid',
        ),
        RemoveConstraintIfExists(
            model_name='item',
            name='app_item_source_valid',
        ),
        AddFieldIfNotExists(
            model_name='anime',
            name='entry_source',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        AddFieldIfNotExists(
            model_name='anime',
            name='scored_at',
            field=app.models.media.ScoreMonitorField(blank=True, default=None, monitor='score', null=True),
        ),
        AddFieldIfNotExists(
            model_name='basicmedia',
            name='entry_source',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        AddFieldIfNotExists(
            model_name='basicmedia',
            name='scored_at',
            field=app.models.media.ScoreMonitorField(blank=True, default=None, monitor='score', null=True),
        ),
        AddFieldIfNotExists(
            model_name='boardgame',
            name='entry_source',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        AddFieldIfNotExists(
            model_name='boardgame',
            name='scored_at',
            field=app.models.media.ScoreMonitorField(blank=True, default=None, monitor='score', null=True),
        ),
        AddFieldIfNotExists(
            model_name='book',
            name='entry_source',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        AddFieldIfNotExists(
            model_name='book',
            name='scored_at',
            field=app.models.media.ScoreMonitorField(blank=True, default=None, monitor='score', null=True),
        ),
        AddFieldIfNotExists(
            model_name='comic',
            name='entry_source',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        AddFieldIfNotExists(
            model_name='comic',
            name='scored_at',
            field=app.models.media.ScoreMonitorField(blank=True, default=None, monitor='score', null=True),
        ),
        AddFieldIfNotExists(
            model_name='comicissue',
            name='entry_source',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        AddFieldIfNotExists(
            model_name='comicissue',
            name='scored_at',
            field=app.models.media.ScoreMonitorField(blank=True, default=None, monitor='score', null=True),
        ),
        AddFieldIfNotExists(
            model_name='episode',
            name='entry_source',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        AddFieldIfNotExists(
            model_name='episode',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        AddFieldIfNotExists(
            model_name='episode',
            name='order_archived',
            field=models.BooleanField(default=False),
        ),
        AddFieldIfNotExists(
            model_name='episode',
            name='rating_only',
            field=models.BooleanField(default=False),
        ),
        AddFieldIfNotExists(
            model_name='episode',
            name='scored_at',
            field=app.models.media.ScoreMonitorField(blank=True, default=None, monitor='score', null=True),
        ),
        AddFieldIfNotExists(
            model_name='game',
            name='entry_source',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        AddFieldIfNotExists(
            model_name='game',
            name='scored_at',
            field=app.models.media.ScoreMonitorField(blank=True, default=None, monitor='score', null=True),
        ),
        AddFieldIfNotExists(
            model_name='historicalanime',
            name='entry_source',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        AddFieldIfNotExists(
            model_name='historicalbasicmedia',
            name='entry_source',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        AddFieldIfNotExists(
            model_name='historicalboardgame',
            name='entry_source',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        AddFieldIfNotExists(
            model_name='historicalbook',
            name='entry_source',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        AddFieldIfNotExists(
            model_name='historicalcomic',
            name='entry_source',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        AddFieldIfNotExists(
            model_name='historicalcomicissue',
            name='entry_source',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        AddFieldIfNotExists(
            model_name='historicalepisode',
            name='order_archived',
            field=models.BooleanField(default=False),
        ),
        AddFieldIfNotExists(
            model_name='historicalepisode',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('In progress', 'In Progress'), ('Planning', 'Planning'), ('Paused', 'Paused'), ('Dropped', 'Dropped')], default='Completed', max_length=20),
        ),
        AddFieldIfNotExists(
            model_name='historicalgame',
            name='entry_source',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        AddFieldIfNotExists(
            model_name='historicalmanga',
            name='entry_source',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        AddFieldIfNotExists(
            model_name='historicalmovie',
            name='entry_source',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        AddFieldIfNotExists(
            model_name='historicalmusic',
            name='entry_source',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        AddFieldIfNotExists(
            model_name='historicalmusic',
            name='origin_url',
            field=models.CharField(blank=True, default='', help_text='Client origin URL for this play, when the scrobble sent one.', max_length=500),
        ),
        AddFieldIfNotExists(
            model_name='historicalpodcast',
            name='entry_source',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        AddFieldIfNotExists(
            model_name='historicalseason',
            name='entry_source',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        AddFieldIfNotExists(
            model_name='historicalseason',
            name='order_archived',
            field=models.BooleanField(default=False),
        ),
        AddFieldIfNotExists(
            model_name='historicaltv',
            name='entry_source',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        AddFieldIfNotExists(
            model_name='item',
            name='metadata_refreshed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        AddFieldIfNotExists(
            model_name='item',
            name='opencritic_checked_at',
            field=models.DateTimeField(blank=True, help_text='When OpenCritic was last asked about this game', null=True),
        ),
        AddFieldIfNotExists(
            model_name='item',
            name='opencritic_id',
            field=models.PositiveIntegerField(blank=True, help_text='Matched OpenCritic game ID', null=True),
        ),
        AddFieldIfNotExists(
            model_name='item',
            name='opencritic_percent_recommended',
            field=models.FloatField(blank=True, help_text='Share of OpenCritic critics who recommend the game', null=True),
        ),
        AddFieldIfNotExists(
            model_name='item',
            name='opencritic_review_count',
            field=models.PositiveIntegerField(blank=True, help_text='Number of top critic reviews on OpenCritic', null=True),
        ),
        AddFieldIfNotExists(
            model_name='item',
            name='opencritic_score',
            field=models.FloatField(blank=True, help_text='OpenCritic top critic average (0-100)', null=True),
        ),
        AddFieldIfNotExists(
            model_name='item',
            name='opencritic_tier',
            field=models.CharField(blank=True, default='', help_text='OpenCritic tier: Mighty, Strong, Fair or Weak', max_length=20),
        ),
        AddFieldIfNotExists(
            model_name='item',
            name='opencritic_url',
            field=models.URLField(blank=True, default='', help_text='OpenCritic page for the matched game', max_length=500),
        ),
        AddFieldIfNotExists(
            model_name='item',
            name='provider_episode_count',
            field=models.PositiveIntegerField(blank=True, help_text='Total episode count reported by the metadata provider', null=True),
        ),
        AddFieldIfNotExists(
            model_name='item',
            name='provider_episode_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        AddFieldIfNotExists(
            model_name='manga',
            name='entry_source',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        AddFieldIfNotExists(
            model_name='manga',
            name='scored_at',
            field=app.models.media.ScoreMonitorField(blank=True, default=None, monitor='score', null=True),
        ),
        AddFieldIfNotExists(
            model_name='movie',
            name='entry_source',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        AddFieldIfNotExists(
            model_name='movie',
            name='scored_at',
            field=app.models.media.ScoreMonitorField(blank=True, default=None, monitor='score', null=True),
        ),
        AddFieldIfNotExists(
            model_name='movieplay',
            name='entry_source',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        AddFieldIfNotExists(
            model_name='music',
            name='entry_source',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        AddFieldIfNotExists(
            model_name='music',
            name='origin_url',
            field=models.CharField(blank=True, default='', help_text='Client origin URL for this play, when the scrobble sent one.', max_length=500),
        ),
        AddFieldIfNotExists(
            model_name='music',
            name='scored_at',
            field=app.models.media.ScoreMonitorField(blank=True, default=None, monitor='score', null=True),
        ),
        AddFieldIfNotExists(
            model_name='person',
            name='profile_backfill_fail_count',
            field=models.PositiveIntegerField(default=0),
        ),
        AddFieldIfNotExists(
            model_name='person',
            name='profile_backfill_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        AddFieldIfNotExists(
            model_name='person',
            name='profile_backfill_next_retry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        AddFieldIfNotExists(
            model_name='person',
            name='profile_backfill_version',
            field=models.PositiveIntegerField(default=0),
        ),
        AddFieldIfNotExists(
            model_name='podcast',
            name='entry_source',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        AddFieldIfNotExists(
            model_name='podcast',
            name='scored_at',
            field=app.models.media.ScoreMonitorField(blank=True, default=None, monitor='score', null=True),
        ),
        AddFieldIfNotExists(
            model_name='season',
            name='entry_source',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        AddFieldIfNotExists(
            model_name='season',
            name='order_archived',
            field=models.BooleanField(default=False),
        ),
        AddFieldIfNotExists(
            model_name='season',
            name='scored_at',
            field=app.models.media.ScoreMonitorField(blank=True, default=None, monitor='score', null=True),
        ),
        AddFieldIfNotExists(
            model_name='tv',
            name='entry_source',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        AddFieldIfNotExists(
            model_name='tv',
            name='scored_at',
            field=app.models.media.ScoreMonitorField(blank=True, default=None, monitor='score', null=True),
        ),
        migrations.AlterField(
            model_name='deletedmedia',
            name='media_type',
            field=models.CharField(choices=[('tv', 'TV Show'), ('season', 'TV Season'), ('episode', 'Episode'), ('movie', 'Movie'), ('anime', 'Anime'), ('manga', 'Manga'), ('game', 'Game'), ('book', 'Book'), ('comic', 'Comic'), ('comicissue', 'Comic Issue'), ('boardgame', 'Board Game'), ('music', 'Music'), ('podcast', 'Podcast'), ('video', 'Video')], max_length=20),
        ),
        migrations.AlterField(
            model_name='deletedmedia',
            name='source',
            field=models.CharField(choices=[('tmdb', 'The Movie Database'), ('tvdb', 'TheTVDB'), ('mal', 'MyAnimeList'), ('mangaupdates', 'MangaUpdates'), ('mangabaka', 'MangaBaka'), ('igdb', 'Internet Game Database'), ('imdb', 'IMDb'), ('openlibrary', 'Open Library'), ('hardcover', 'Hardcover'), ('googlebooks', 'Google Books'), ('comicvine', 'Comic Vine'), ('gcd', 'Grand Comics Database'), ('bgg', 'BoardGameGeek'), ('musicbrainz', 'MusicBrainz'), ('pocketcasts', 'Pocket Casts'), ('gpodder', 'GPodder'), ('audiobookshelf', 'Audiobookshelf'), ('storyteller', 'Storyteller'), ('plex', 'Plex'), ('manual', 'Manual'), ('youtube', 'YouTube')], max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='library_media_type',
            field=models.CharField(blank=True, choices=[('tv', 'TV Show'), ('season', 'TV Season'), ('episode', 'Episode'), ('movie', 'Movie'), ('anime', 'Anime'), ('manga', 'Manga'), ('game', 'Game'), ('book', 'Book'), ('comic', 'Comic'), ('comicissue', 'Comic Issue'), ('boardgame', 'Board Game'), ('music', 'Music'), ('podcast', 'Podcast'), ('video', 'Video')], default='', help_text='Library bucket for this item (e.g. grouped anime stored on TV rows).', max_length=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='media_type',
            field=models.CharField(choices=[('tv', 'TV Show'), ('season', 'TV Season'), ('episode', 'Episode'), ('movie', 'Movie'), ('anime', 'Anime'), ('manga', 'Manga'), ('game', 'Game'), ('book', 'Book'), ('comic', 'Comic'), ('comicissue', 'Comic Issue'), ('boardgame', 'Board Game'), ('music', 'Music'), ('podcast', 'Podcast'), ('video', 'Video')], default='movie', max_length=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='source',
            field=models.CharField(choices=[('tmdb', 'The Movie Database'), ('tvdb', 'TheTVDB'), ('mal', 'MyAnimeList'), ('mangaupdates', 'MangaUpdates'), ('mangabaka', 'MangaBaka'), ('igdb', 'Internet Game Database'), ('imdb', 'IMDb'), ('openlibrary', 'Open Library'), ('hardcover', 'Hardcover'), ('googlebooks', 'Google Books'), ('comicvine', 'Comic Vine'), ('gcd', 'Grand Comics Database'), ('bgg', 'BoardGameGeek'), ('musicbrainz', 'MusicBrainz'), ('pocketcasts', 'Pocket Casts'), ('gpodder', 'GPodder'), ('audiobookshelf', 'Audiobookshelf'), ('storyteller', 'Storyteller'), ('plex', 'Plex'), ('manual', 'Manual'), ('youtube', 'YouTube')], max_length=20),
        ),
        migrations.AlterField(
            model_name='itemproviderlink',
            name='provider',
            field=models.CharField(choices=[('tmdb', 'The Movie Database'), ('tvdb', 'TheTVDB'), ('mal', 'MyAnimeList'), ('mangaupdates', 'MangaUpdates'), ('mangabaka', 'MangaBaka'), ('igdb', 'Internet Game Database'), ('imdb', 'IMDb'), ('openlibrary', 'Open Library'), ('hardcover', 'Hardcover'), ('googlebooks', 'Google Books'), ('comicvine', 'Comic Vine'), ('gcd', 'Grand Comics Database'), ('bgg', 'BoardGameGeek'), ('musicbrainz', 'MusicBrainz'), ('pocketcasts', 'Pocket Casts'), ('gpodder', 'GPodder'), ('audiobookshelf', 'Audiobookshelf'), ('storyteller', 'Storyteller'), ('plex', 'Plex'), ('manual', 'Manual'), ('youtube', 'YouTube')], max_length=20),
        ),
        migrations.AlterField(
            model_name='itemproviderlink',
            name='provider_media_type',
            field=models.CharField(choices=[('tv', 'TV Show'), ('season', 'TV Season'), ('episode', 'Episode'), ('movie', 'Movie'), ('anime', 'Anime'), ('manga', 'Manga'), ('game', 'Game'), ('book', 'Book'), ('comic', 'Comic'), ('comicissue', 'Comic Issue'), ('boardgame', 'Board Game'), ('music', 'Music'), ('podcast', 'Podcast'), ('video', 'Video')], max_length=10),
        ),
        migrations.AlterField(
            model_name='metadatabackfillstate',
            name='field',
            field=models.CharField(choices=[('runtime', 'Runtime'), ('genres', 'Genres'), ('credits', 'Credits'), ('release', 'Release Date'), ('discover', 'Discover Metadata'), ('game_lengths', 'Game Lengths'), ('trakt_popularity', 'Trakt Popularity'), ('igdb_ratings', 'IGDB Ratings'), ('watch_providers', 'Watch Providers'), ('external_ids', 'External IDs'), ('studios', 'Studios'), ('imdb_match', 'IMDB Title Match'), ('status', 'Status'), ('tvdb_migration', 'TVDB Migration')], max_length=20),
        ),
        migrations.AlterField(
            model_name='metadataproviderpreference',
            name='provider',
            field=models.CharField(blank=True, choices=[('tmdb', 'The Movie Database'), ('tvdb', 'TheTVDB'), ('mal', 'MyAnimeList'), ('mangaupdates', 'MangaUpdates'), ('mangabaka', 'MangaBaka'), ('igdb', 'Internet Game Database'), ('imdb', 'IMDb'), ('openlibrary', 'Open Library'), ('hardcover', 'Hardcover'), ('googlebooks', 'Google Books'), ('comicvine', 'Comic Vine'), ('gcd', 'Grand Comics Database'), ('bgg', 'BoardGameGeek'), ('musicbrainz', 'MusicBrainz'), ('pocketcasts', 'Pocket Casts'), ('gpodder', 'GPodder'), ('audiobookshelf', 'Audiobookshelf'), ('storyteller', 'Storyteller'), ('plex', 'Plex'), ('manual', 'Manual'), ('youtube', 'YouTube')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='source',
            field=models.CharField(choices=[('tmdb', 'The Movie Database'), ('tvdb', 'TheTVDB'), ('mal', 'MyAnimeList'), ('mangaupdates', 'MangaUpdates'), ('mangabaka', 'MangaBaka'), ('igdb', 'Internet Game Database'), ('imdb', 'IMDb'), ('openlibrary', 'Open Library'), ('hardcover', 'Hardcover'), ('googlebooks', 'Google Books'), ('comicvine', 'Comic Vine'), ('gcd', 'Grand Comics Database'), ('bgg', 'BoardGameGeek'), ('musicbrainz', 'MusicBrainz'), ('pocketcasts', 'Pocket Casts'), ('gpodder', 'GPodder'), ('audiobookshelf', 'Audiobookshelf'), ('storyteller', 'Storyteller'), ('plex', 'Plex'), ('manual', 'Manual'), ('youtube', 'YouTube')], default='tmdb', max_length=20),
        ),
        migrations.AlterField(
            model_name='podcastshow',
            name='source',
            field=models.CharField(choices=[('tmdb', 'The Movie Database'), ('tvdb', 'TheTVDB'), ('mal', 'MyAnimeList'), ('mangaupdates', 'MangaUpdates'), ('mangabaka', 'MangaBaka'), ('igdb', 'Internet Game Database'), ('imdb', 'IMDb'), ('openlibrary', 'Open Library'), ('hardcover', 'Hardcover'), ('googlebooks', 'Google Books'), ('comicvine', 'Comic Vine'), ('gcd', 'Grand Comics Database'), ('bgg', 'BoardGameGeek'), ('musicbrainz', 'MusicBrainz'), ('pocketcasts', 'Pocket Casts'), ('gpodder', 'GPodder'), ('audiobookshelf', 'Audiobookshelf'), ('storyteller', 'Storyteller'), ('plex', 'Plex'), ('manual', 'Manual'), ('youtube', 'YouTube')], default='pocketcasts', help_text='Podcast provider source for this show', max_length=20),
        ),
        migrations.AlterField(
            model_name='studio',
            name='source',
            field=models.CharField(choices=[('tmdb', 'The Movie Database'), ('tvdb', 'TheTVDB'), ('mal', 'MyAnimeList'), ('mangaupdates', 'MangaUpdates'), ('mangabaka', 'MangaBaka'), ('igdb', 'Internet Game Database'), ('imdb', 'IMDb'), ('openlibrary', 'Open Library'), ('hardcover', 'Hardcover'), ('googlebooks', 'Google Books'), ('comicvine', 'Comic Vine'), ('gcd', 'Grand Comics Database'), ('bgg', 'BoardGameGeek'), ('musicbrainz', 'MusicBrainz'), ('pocketcasts', 'Pocket Casts'), ('gpodder', 'GPodder'), ('audiobookshelf', 'Audiobookshelf'), ('storyteller', 'Storyteller'), ('plex', 'Plex'), ('manual', 'Manual'), ('youtube', 'YouTube')], default='tmdb', max_length=20),
        ),
        AddIndexIfNotExists(
            model_name='episode',
            index=models.Index(fields=['end_date'], name='app_episode_end_date_idx'),
        ),
        AddIndexIfNotExists(
            model_name='person',
            index=models.Index(fields=['source', 'profile_backfill_version'], name='app_person_source_5f8272_idx'),
        ),
        AddIndexIfNotExists(
            model_name='podcastepisode',
            index=models.Index(fields=['episode_uuid'], name='podcast_ep_uuid_idx'),
        ),
        AddConstraintIfNotExists(
            model_name='episode',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__isnull', False), models.Q(('external_id', ''), _negated=True)), fields=('related_season', 'item', 'external_id'), name='app_episode_unique_episode_external_id'),
        ),
        AddFieldIfNotExists(
            model_name='episodeorder',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='episode_orders', to='app.item'),
        ),
        AddFieldIfNotExists(
            model_name='historicaltv',
            name='active_episode_order',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.episodeorder'),
        ),
        AddFieldIfNotExists(
            model_name='item',
            name='episode_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='app.episodeorder'),
        ),
        AddFieldIfNotExists(
            model_name='tv',
            name='active_episode_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trackers', to='app.episodeorder'),
        ),
        AddConstraintIfNotExists(
            model_name='item',
            constraint=models.CheckConstraint(condition=models.Q(('source__in', ['tmdb', 'tvdb', 'mal', 'mangaupdates', 'mangabaka', 'igdb', 'imdb', 'openlibrary', 'hardcover', 'googlebooks', 'comicvine', 'gcd', 'bgg', 'musicbrainz', 'pocketcasts', 'gpodder', 'audiobookshelf', 'storyteller', 'plex', 'manual', 'youtube'])), name='app_item_source_valid'),
        ),
        AddConstraintIfNotExists(
            model_name='item',
            constraint=models.CheckConstraint(condition=models.Q(('media_type__in', ['tv', 'season', 'episode', 'movie', 'anime', 'manga', 'game', 'book', 'comic', 'comicissue', 'boardgame', 'music', 'podcast', 'video'])), name='app_item_media_type_valid'),
        ),
        AddConstraintIfNotExists(
            model_name='item',
            constraint=models.CheckConstraint(condition=models.Q(('library_media_type', ''), ('library_media_type__in', ['tv', 'season', 'episode', 'movie', 'anime', 'manga', 'game', 'book', 'comic', 'comicissue', 'boardgame', 'music', 'podcast', 'video']), _connector='OR'), name='app_item_library_media_type_valid'),
        ),
        AddFieldIfNotExists(
            model_name='episodeorderchange',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.episodeorder'),
        ),
        AddFieldIfNotExists(
            model_name='episodeorderchange',
            name='tv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tv'),
        ),
        AddFieldIfNotExists(
            model_name='episodeorderchange',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        AddFieldIfNotExists(
            model_name='historicalvideo',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        AddFieldIfNotExists(
            model_name='historicalvideo',
            name='import_run',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The import run that created or last touched this row, if any.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='integrations.importrun'),
        ),
        AddFieldIfNotExists(
            model_name='progresschange',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_changes', to='app.item'),
        ),
        AddFieldIfNotExists(
            model_name='progresschange',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_changes', to=settings.AUTH_USER_MODEL),
        ),
        AddFieldIfNotExists(
            model_name='statisticsdirtyday',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        AddFieldIfNotExists(
            model_name='statisticssnapshot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        AddFieldIfNotExists(
            model_name='video',
            name='import_run',
            field=models.ForeignKey(blank=True, help_text='The import run that created or last touched this row, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='integrations.importrun'),
        ),
        AddFieldIfNotExists(
            model_name='video',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.item'),
        ),
        AddFieldIfNotExists(
            model_name='video',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        AddFieldIfNotExists(
            model_name='videoplay',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plays', to='app.video'),
        ),
        AddConstraintIfNotExists(
            model_name='episodeorder',
            constraint=models.UniqueConstraint(fields=('show', 'provider', 'series_id', 'key', 'revision'), name='app_episode_order_revision_unique'),
        ),
        AddIndexIfNotExists(
            model_name='progresschange',
            index=models.Index(fields=['user', 'sequence'], name='app_progres_user_id_03f694_idx'),
        ),
        AddIndexIfNotExists(
            model_name='progresschange',
            index=models.Index(fields=['created_at'], name='app_progres_created_a24cd5_idx'),
        ),
        AddConstraintIfNotExists(
            model_name='progresschange',
            constraint=models.UniqueConstraint(fields=('user', 'sequence'), name='unique_progress_change_sequence'),
        ),
        AddConstraintIfNotExists(
            model_name='statisticsdirtyday',
            constraint=models.UniqueConstraint(fields=('user', 'day'), name='statistics_dirty_day_unique_user_day'),
        ),
        AddConstraintIfNotExists(
            model_name='statisticssnapshot',
            constraint=models.UniqueConstraint(fields=('user', 'range_name'), name='statistics_snapshot_unique_user_range'),
        ),
        migrations.AlterUniqueTogether(
            name='video',
            unique_together={('item', 'user')},
        ),
        AddConstraintIfNotExists(
            model_name='videoplay',
            constraint=models.UniqueConstraint(fields=('video', 'external_id'), name='app_videoplay_unique_video_external_id'),
        ),
        migrations.RunPython(backfill_episode_history_status, migrations.RunPython.noop),
    ]
