# Generated by Django 5.2.16 on 2026-08-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0027_alter_collectionsourcestate_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="jellyfinaccount",
            name="last_pull_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jellyfinaccount",
            name="last_pull_error_message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="jellyfinaccount",
            name="library_backfill_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jellyfinaccount",
            name="playback_reporting_available",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="Whether the Playback Reporting plugin's API was reachable with this account's key. Unknown (null) until the first pull runs.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="jellyfinaccount",
            name="playback_reporting_last_rowid",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jellyfinaccount",
            name="pull_history_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Automatically pull Jellyfin watch history on a recurring schedule",
            ),
        ),
    ]
