# Generated by Django 5.2.16 on 2026-08-26 23:49, hand-edited to preserve data.
#
# The autodetector's first pass emitted DeleteModel(RadarrAccount)/CreateModel(RadarrInstance)
# (and same for Sonarr), which would silently drop every user's existing connection
# (including encrypted API keys) on migrate. This version uses RenameModel + AlterField
# instead so existing rows carry over unchanged.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _column_exists(schema_editor, table_name, column_name):
    """Return True when a database column already exists."""
    connection = schema_editor.connection
    if connection.vendor == "postgresql":
        with connection.cursor() as cursor:
            cursor.execute(
                "SELECT 1 FROM information_schema.columns "
                "WHERE table_schema = current_schema() "
                "AND table_name = %s AND column_name = %s",
                [table_name, column_name],
            )
            return cursor.fetchone() is not None
    with connection.cursor() as cursor:
        description = connection.introspection.get_table_description(cursor, table_name)
        columns = {getattr(column, "name", column[0]) for column in description}
        return column_name in columns


def _constraint_exists(schema_editor, table_name, constraint_name):
    """Return True when a Postgres constraint already exists.

    Only meaningful on Postgres: a plain UniqueConstraint added at model
    creation time is baked directly into SQLite's CREATE TABLE statement
    (not a separately named index), so there's no reliable, cheap way to
    detect it by name there. See RemoveConstraintIfExists below for how
    that's handled instead of relying on this check.
    """
    connection = schema_editor.connection
    if connection.vendor != "postgresql":
        return False
    with connection.cursor() as cursor:
        cursor.execute(
            "SELECT 1 FROM pg_constraint WHERE conname = %s",
            [constraint_name],
        )
        return cursor.fetchone() is not None


class AddFieldIfNotExists(migrations.AddField):
    """Add a field only when the backing column doesn't already exist."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        to_model = to_state.apps.get_model(app_label, self.model_name)
        field = to_model._meta.get_field(self.name)
        if _column_exists(schema_editor, to_model._meta.db_table, field.column):
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)


class AddConstraintIfNotExists(migrations.AddConstraint):
    """Add a constraint only when it doesn't already exist."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        to_model = to_state.apps.get_model(app_label, self.model_name)
        if _constraint_exists(schema_editor, to_model._meta.db_table, self.constraint.name):
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)


class RemoveConstraintIfExists(migrations.RemoveConstraint):
    """Remove a constraint only when it exists.

    On Postgres this is a real existence check (idempotency safety net for
    replaying this migration against a database where the constraint was
    already dropped by hand). On SQLite there's no cheap way to check --
    a plain UniqueConstraint from CreateModel is baked into the table's
    CREATE TABLE statement rather than stored as a separately named index --
    so this always proceeds there instead. That's safe: SQLite implements
    constraint removal via a full table rebuild from the target state, which
    is idempotent regardless of the constraint's current physical form.
    """

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        connection = schema_editor.connection
        if connection.vendor == "postgresql":
            from_model = from_state.apps.get_model(app_label, self.model_name)
            if not _constraint_exists(schema_editor, from_model._meta.db_table, self.name):
                return
        super().database_forwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0166_item_source_url"),
        ("integrations", "0029_jellyfin_pull_schedule_backfill"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="RadarrAccount",
            new_name="RadarrInstance",
        ),
        migrations.RenameModel(
            old_name="SonarrAccount",
            new_name="SonarrInstance",
        ),
        migrations.AlterModelOptions(
            name="radarrinstance",
            options={
                "verbose_name": "Radarr instance",
                "verbose_name_plural": "Radarr instances",
            },
        ),
        migrations.AlterModelOptions(
            name="sonarrinstance",
            options={
                "verbose_name": "Sonarr instance",
                "verbose_name_plural": "Sonarr instances",
            },
        ),
        AddFieldIfNotExists(
            model_name="radarrinstance",
            name="name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional label to distinguish multiple instances, e.g. '4K' or 'Anime'",
                max_length=100,
            ),
        ),
        AddFieldIfNotExists(
            model_name="sonarrinstance",
            name="name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional label to distinguish multiple instances, e.g. '4K' or 'Anime'",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="radarrinstance",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="radarr_instances",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="sonarrinstance",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sonarr_instances",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        AddConstraintIfNotExists(
            model_name="radarrinstance",
            constraint=models.UniqueConstraint(
                fields=("user", "base_url"),
                name="integrations_radarrinstance_unique_user_base_url",
            ),
        ),
        AddConstraintIfNotExists(
            model_name="sonarrinstance",
            constraint=models.UniqueConstraint(
                fields=("user", "base_url"),
                name="integrations_sonarrinstance_unique_user_base_url",
            ),
        ),
        RemoveConstraintIfExists(
            model_name="collectionsourcestate",
            name="integrations_collectionsourcestate_unique_user_item_source",
        ),
        AddFieldIfNotExists(
            model_name="collectionsourcestate",
            name="source_instance_id",
            field=models.PositiveIntegerField(
                blank=True,
                help_text=(
                    "PK of the RadarrInstance/SonarrInstance this row came from; "
                    "unused for plex/jellyfin"
                ),
                null=True,
            ),
        ),
        AddConstraintIfNotExists(
            model_name="collectionsourcestate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_instance_id__isnull", True)),
                fields=("user", "item", "source"),
                name="integrations_collectionsourcestate_unique_user_item_source",
            ),
        ),
        AddConstraintIfNotExists(
            model_name="collectionsourcestate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_instance_id__isnull", False)),
                fields=("user", "item", "source", "source_instance_id"),
                name="integrations_collectionsourcestate_unique_user_item_source_instance",
            ),
        ),
    ]
