# Generated by Django 5.2.16 on 2026-08-28 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0031_backfill_collectionsourcestate_instance'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlexLibrarySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_identifier', models.CharField(max_length=255)),
                ('section_id', models.CharField(max_length=50)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('media_type', models.CharField(max_length=20)),
                ('plex_uri', models.URLField(blank=True, default='')),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete'), ('error', 'Error')], default='pending', max_length=10)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_sections', to='integrations.plexaccount')),
            ],
        ),
        migrations.CreateModel(
            name='PlexLibraryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_key', models.CharField(max_length=50)),
                ('media_type', models.CharField(max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('tmdb_id', models.CharField(blank=True, default='', max_length=32)),
                ('imdb_id', models.CharField(blank=True, default='', max_length=32)),
                ('tvdb_id', models.CharField(blank=True, default='', max_length=32)),
                ('season_number', models.PositiveIntegerField(blank=True, null=True)),
                ('episode_number', models.PositiveIntegerField(blank=True, null=True)),
                ('scan_token', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='integrations.plexlibrarysection')),
            ],
        ),
        migrations.AddIndex(
            model_name='plexlibrarysection',
            index=models.Index(fields=['account', 'media_type', 'sync_status'], name='plexsection_availability_idx'),
        ),
        migrations.AddConstraint(
            model_name='plexlibrarysection',
            constraint=models.UniqueConstraint(fields=('account', 'machine_identifier', 'section_id'), name='integrations_plexlibrarysection_unique_source'),
        ),
        migrations.AddIndex(
            model_name='plexlibraryitem',
            index=models.Index(fields=['media_type', 'tmdb_id'], name='plexitem_tmdb_idx'),
        ),
        migrations.AddIndex(
            model_name='plexlibraryitem',
            index=models.Index(fields=['media_type', 'imdb_id'], name='plexitem_imdb_idx'),
        ),
        migrations.AddIndex(
            model_name='plexlibraryitem',
            index=models.Index(fields=['media_type', 'tvdb_id'], name='plexitem_tvdb_idx'),
        ),
        migrations.AddConstraint(
            model_name='plexlibraryitem',
            constraint=models.UniqueConstraint(fields=('section', 'rating_key'), name='integrations_plexlibraryitem_unique_rating_key'),
        ),
    ]
