# Generated by Django 5.2.16 on 2026-09-08 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0033_plex_library_index_schedule'),
        ('integrations', '0036_merge_20260905_1122'),
    ]

    operations = [
    ]
