# Generated by Django 5.2.17 on 2026-10-07 18:16

import secrets

import django.core.serializers.json
import django.db.models.deletion
import django.utils.timezone
import integrations.oauth_models
from django.conf import settings
from django.db import migrations, models

from importlib import import_module

_constraint_operations = import_module("integrations.migrations.0030_radarrinstance_sonarrinstance_and_more")
_index_operations = import_module("app.migrations.0134_item_app_item_media_lookup_idx")
AddFieldIfNotExists = _constraint_operations.AddFieldIfNotExists
AddConstraintIfNotExists = _constraint_operations.AddConstraintIfNotExists
RemoveConstraintIfExists = _constraint_operations.RemoveConstraintIfExists
AddIndexIfNotExists = _index_operations.AddIndexIfNotExists


def _capabilities_for(user, account):
    """Preserve only directions enabled by the legacy Jellyfin switches."""
    capabilities = []
    directions = []
    if user.jellyfin_mark_played_enabled:
        capabilities.append("watched.write_played")
    if user.jellyfin_mark_unplayed_enabled:
        capabilities.append("watched.write_unplayed")
    if capabilities:
        directions.append("inbound")
    if account:
        if account.pull_history_enabled:
            capabilities.append("watched.read")
            directions.append("inbound")
        pushing = account.scheduled_push_enabled or account.instant_push_enabled
        if pushing and account.push_watched_enabled:
            capabilities.append("watched.push_played")
        if pushing and account.push_unwatched_enabled:
            capabilities.append("watched.push_unplayed")
        if pushing and (account.push_watched_enabled or account.push_unwatched_enabled):
            directions.append("outbound")
    return sorted(set(capabilities)), sorted(set(directions))


def preserve_jellyfin_authorizations(apps, schema_editor):
    """Translate enabled directions without granting dormant outbound writes."""
    alias = schema_editor.connection.alias
    users = apps.get_model("users", "User").objects.using(alias)
    accounts = {a.user_id: a for a in apps.get_model("integrations", "JellyfinAccount").objects.using(alias).all()}
    bindings = apps.get_model("integrations", "SyncBinding").objects.using(alias)
    sequences = apps.get_model("app", "WatchStateSequence").objects.using(alias)
    candidates = set(accounts)
    candidates.update(users.filter(jellyfin_mark_played_enabled=True).values_list("pk", flat=True))
    candidates.update(users.filter(jellyfin_mark_unplayed_enabled=True).values_list("pk", flat=True))
    for user in users.filter(pk__in=candidates).iterator():
        account = accounts.get(user.pk)
        capabilities, directions = _capabilities_for(user, account)
        binding, created = bindings.get_or_create(
            user_id=user.pk, client_kind="jellyfin", instance_key="",
            profile_key=account.jellyfin_user_id if account else "",
            defaults={
                "origin_key": "jellyfin_" + secrets.token_urlsafe(16),
                "approved_capabilities": sorted(set(capabilities)),
                "approved_directions": sorted(set(directions)),
                "status": "active" if capabilities else "pending",
                "kill_switch": False, "label": account.base_url if account else "",
            },
        )
        if created and capabilities:
            sequences.update_or_create(user_id=user.pk, defaults={"emit_changes": True})


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0182_episodeorder_episodeorderchange_historicalvideo_and_more'),
        ('integrations', '0037_merge_20260908_1855'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('catalog_ids', models.JSONField(default=list)),
                ('allow_playback_start', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Catalog grant',
                'verbose_name_plural': 'Catalog grants',
            },
        ),
        migrations.CreateModel(
            name='EmbyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.URLField(help_text='Emby server URL')),
                ('api_key', models.TextField(help_text='Encrypted Emby API key')),
                ('emby_user_id', models.CharField(blank=True, default='', max_length=255)),
                ('emby_username', models.CharField(blank=True, default='', max_length=255)),
                ('server_id', models.CharField(blank=True, default='', max_length=255)),
                ('connection_broken', models.BooleanField(default=False)),
                ('last_error_message', models.TextField(blank=True, default='')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Emby account',
                'verbose_name_plural': 'Emby accounts',
            },
        ),
        migrations.CreateModel(
            name='ExternalReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integration', models.CharField(max_length=32)),
                ('source_account', models.CharField(blank=True, default='', max_length=255)),
                ('external_namespace', models.CharField(max_length=32)),
                ('external_identity', models.CharField(max_length=500)),
                ('media_type', models.CharField(choices=[('tv', 'TV Show'), ('movie', 'Movie'), ('episode', 'Episode')], max_length=10)),
                ('review_status', models.CharField(choices=[('resolved', 'Resolved automatically'), ('needs_review', 'Needs review'), ('corrected', 'Corrected'), ('ignored', 'Ignored')], default='resolved', max_length=20)),
                ('episode_mapping', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('decision_note', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportChunkReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(default='persist', max_length=16)),
                ('start', models.PositiveIntegerField()),
                ('end', models.PositiveIntegerField()),
                ('digest', models.CharField(max_length=64)),
                ('fence', models.PositiveIntegerField()),
                ('rows_persisted', models.PositiveIntegerField(default=0)),
                ('metrics', models.JSONField(default=dict)),
                ('publication_pending', models.BooleanField(default=True)),
                ('committed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImportOverwriteTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.PositiveIntegerField()),
                ('model_label', models.CharField(max_length=100)),
                ('original_pk', models.PositiveBigIntegerField()),
                ('fingerprint', models.CharField(max_length=64)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='KapowarrInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', help_text='Optional label to distinguish multiple instances', max_length=100)),
                ('base_url', models.URLField(help_text='Kapowarr server URL')),
                ('api_key', models.TextField(help_text='Encrypted Kapowarr API key')),
                ('connection_broken', models.BooleanField(default=False)),
                ('last_error_message', models.TextField(blank=True, default='')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kapowarr instance',
                'verbose_name_plural': 'Kapowarr instances',
            },
        ),
        migrations.CreateModel(
            name='KavitaAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.URLField(help_text='Server URL')),
                ('api_key', models.TextField(help_text='Encrypted API key')),
                ('create_missing', models.BooleanField(default=True, help_text='Create Floppy items when server items cannot be matched')),
                ('sync_interval_minutes', models.PositiveSmallIntegerField(default=15, help_text='How often reading progress is synced')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('connection_broken', models.BooleanField(default=False)),
                ('last_error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kavita account',
                'verbose_name_plural': 'Kavita accounts',
            },
        ),
        migrations.CreateModel(
            name='KavitaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kavita_key', models.CharField(max_length=64)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kavita link',
                'verbose_name_plural': 'Kavita links',
            },
        ),
        migrations.CreateModel(
            name='KodiAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.URLField(help_text='Kodi JSON-RPC endpoint URL')),
                ('username', models.CharField(blank=True, default='', max_length=255)),
                ('password', models.TextField(blank=True, default='', help_text='Encrypted Kodi JSON-RPC password')),
                ('instance_uuid', models.CharField(blank=True, default='', max_length=255)),
                ('connection_broken', models.BooleanField(default=False)),
                ('last_error_message', models.TextField(blank=True, default='')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kodi account',
                'verbose_name_plural': 'Kodi accounts',
            },
        ),
        migrations.CreateModel(
            name='KomgaAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.URLField(help_text='Server URL')),
                ('api_key', models.TextField(help_text='Encrypted API key')),
                ('create_missing', models.BooleanField(default=True, help_text='Create Floppy items when server items cannot be matched')),
                ('sync_interval_minutes', models.PositiveSmallIntegerField(default=15, help_text='How often reading progress is synced')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('connection_broken', models.BooleanField(default=False)),
                ('last_error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Komga account',
                'verbose_name_plural': 'Komga accounts',
            },
        ),
        migrations.CreateModel(
            name='KomgaBookLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('komga_book_id', models.CharField(max_length=64)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Komga book link',
                'verbose_name_plural': 'Komga book links',
            },
        ),
        migrations.CreateModel(
            name='MylarInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', help_text='Optional label to distinguish multiple instances', max_length=100)),
                ('base_url', models.URLField(help_text='Mylar3 server URL')),
                ('api_key', models.TextField(help_text='Encrypted Mylar3 API key')),
                ('connection_broken', models.BooleanField(default=False)),
                ('last_error_message', models.TextField(blank=True, default='')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mylar3 instance',
                'verbose_name_plural': 'Mylar3 instances',
            },
        ),
        migrations.CreateModel(
            name='OAuthClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(db_index=True, max_length=96, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('allowed_scopes', models.JSONField(default=integrations.oauth_models.default_oauth_scopes)),
                ('grant_types', models.JSONField(default=integrations.oauth_models.default_oauth_grant_types)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name', 'client_id'],
            },
        ),
        migrations.CreateModel(
            name='OAuthDeviceAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_code_digest', models.CharField(db_index=True, max_length=64, unique=True)),
                ('user_code_digest', models.CharField(db_index=True, max_length=64, unique=True)),
                ('requested_scopes', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('interval', models.PositiveSmallIntegerField(default=5)),
                ('last_polled_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('denied_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OAuthRefreshToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_digest', models.CharField(db_index=True, max_length=64, unique=True)),
                ('token_prefix', models.CharField(blank=True, default='', max_length=20)),
                ('scopes', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutboundStateDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_revision', models.PositiveIntegerField(default=0)),
                ('target_digest', models.CharField(blank=True, default='', max_length=64)),
                ('intent', models.BooleanField(default=True, help_text='True to mark played remotely, False to mark unplayed.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_flight', 'In flight'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('superseded', 'Superseded'), ('skipped', 'Skipped')], default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_message', models.TextField(blank=True, default='')),
                ('client_event_id', models.CharField(blank=True, default='', max_length=255)),
                ('correlation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('readback_digest', models.CharField(blank=True, default='', max_length=64)),
                ('echo_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Outbound state delivery',
                'verbose_name_plural': 'Outbound state deliveries',
                'ordering': ['binding', 'item', 'target_revision'],
            },
        ),
        migrations.CreateModel(
            name='PreparedImportEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.PositiveIntegerField()),
                ('model_label', models.CharField(max_length=100)),
                ('operation', models.CharField(max_length=16)),
                ('payload', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('digest', models.CharField(max_length=64)),
                ('persisted_pk', models.PositiveBigIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['ordinal'],
            },
        ),
        migrations.CreateModel(
            name='ProviderStateObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, default='', max_length=255)),
                ('watched', models.BooleanField(default=False)),
                ('play_count', models.PositiveIntegerField(default=0)),
                ('watched_at', models.DateTimeField(blank=True, null=True)),
                ('provider_digest', models.CharField(blank=True, default='', max_length=64)),
                ('local_revision_at_observation', models.PositiveIntegerField(default=0)),
                ('local_digest_at_observation', models.CharField(blank=True, default='', max_length=64)),
                ('source', models.CharField(blank=True, default='', max_length=32)),
                ('observed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Provider state observation',
                'verbose_name_plural': 'Provider state observations',
            },
        ),
        migrations.CreateModel(
            name='RemoteAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manifest_url', models.URLField(max_length=2048)),
                ('addon_id', models.CharField(blank=True, default='', max_length=255)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('version', models.CharField(blank=True, default='', max_length=64)),
                ('description', models.TextField(blank=True, default='')),
                ('manifest', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('enabled', models.BooleanField(default=True)),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(blank=True, default='', max_length=32)),
                ('last_error_code', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Remote add-on',
                'verbose_name_plural': 'Remote add-ons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StateConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('divergent_watched', 'Both sides changed watched state'), ('digest_mismatch', 'States diverged'), ('unattributable_unwatch', 'Nothing identifiable to retract'), ('ambiguous_match', 'More than one item matched')], max_length=32)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=16)),
                ('local_snapshot', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('remote_snapshot', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('base_snapshot', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('occurrence_count', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'State conflict',
                'verbose_name_plural': 'State conflicts',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_kind', models.CharField(choices=[('plex', 'Plex'), ('jellyfin', 'Jellyfin'), ('emby', 'Emby'), ('kodi', 'Kodi'), ('stremio', 'Stremio'), ('audiobookshelf', 'Audiobookshelf'), ('generic', 'Generic client')], max_length=32)),
                ('instance_key', models.CharField(blank=True, default='', max_length=255)),
                ('profile_key', models.CharField(blank=True, default='', max_length=255)),
                ('origin_key', models.CharField(max_length=128, unique=True)),
                ('approved_capabilities', models.JSONField(default=list)),
                ('approved_directions', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending approval'), ('active', 'Active'), ('needs_reapproval', 'Needs reapproval'), ('disabled', 'Disabled')], default='pending', max_length=24)),
                ('kill_switch', models.BooleanField(default=False)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('last_reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Sync binding',
                'verbose_name_plural': 'Sync bindings',
                'ordering': ['user', 'client_kind', 'instance_key'],
            },
        ),
        migrations.CreateModel(
            name='SyncCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(max_length=64)),
                ('direction', models.CharField(choices=[('inbound', 'Provider to Floppy'), ('outbound', 'Floppy to provider')], max_length=16)),
                ('cursor', models.CharField(blank=True, default='', max_length=512)),
                ('last_sequence', models.BigIntegerField(default=0)),
                ('provider_cursor', models.CharField(blank=True, default='', max_length=512)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sync checkpoint',
                'verbose_name_plural': 'Sync checkpoints',
            },
        ),
        migrations.CreateModel(
            name='UnresolvedExternalReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespace', models.CharField(max_length=32)),
                ('value', models.CharField(max_length=255)),
                ('reason_code', models.CharField(choices=[('unknown_id', 'No matching item'), ('unsupported_namespace', 'Identifier type unsupported'), ('ambiguous', 'More than one item matched'), ('unsupported_media_type', 'Media type unsupported')], max_length=32)),
                ('context', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('occurrence_count', models.PositiveIntegerField(default=1)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Unresolved external reference',
                'verbose_name_plural': 'Unresolved external references',
                'ordering': ['-last_seen_at'],
            },
        ),
        RemoveConstraintIfExists(
            model_name='integrationeventreceipt',
            name='unique_user_client_event_id',
        ),
        RemoveConstraintIfExists(
            model_name='plexwatchlistsyncitem',
            name='integrations_plexwatchlistsyncitem_unique_user_item_source',
        ),
        AddFieldIfNotExists(
            model_name='audiobookshelfaccount',
            name='abs_user_id',
            field=models.CharField(blank=True, default='', help_text='Audiobookshelf user id, used to scope a sync binding.', max_length=255),
        ),
        AddFieldIfNotExists(
            model_name='gpodderaccount',
            name='last_full_resync_at',
            field=models.DateTimeField(blank=True, help_text='Last time a full (non-incremental) GPodder history resync ran', null=True),
        ),
        AddFieldIfNotExists(
            model_name='importrun',
            name='chunk_rows',
            field=models.PositiveIntegerField(default=100),
        ),
        AddFieldIfNotExists(
            model_name='importrun',
            name='commit_cursor',
            field=models.PositiveIntegerField(default=0),
        ),
        AddFieldIfNotExists(
            model_name='importrun',
            name='fence',
            field=models.PositiveIntegerField(default=0),
        ),
        AddFieldIfNotExists(
            model_name='importrun',
            name='lease_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        AddFieldIfNotExists(
            model_name='importrun',
            name='lease_owner',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        AddFieldIfNotExists(
            model_name='importrun',
            name='phase',
            field=models.CharField(blank=True, default='', max_length=24),
        ),
        AddFieldIfNotExists(
            model_name='importrun',
            name='prepared_digest',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        AddFieldIfNotExists(
            model_name='importrun',
            name='prepared_state',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        AddFieldIfNotExists(
            model_name='importrun',
            name='terminal_error',
            field=models.JSONField(default=dict),
        ),
        AddFieldIfNotExists(
            model_name='integrationtoken',
            name='writable_list_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        AddFieldIfNotExists(
            model_name='jellyfinaccount',
            name='server_id',
            field=models.CharField(blank=True, default='', help_text='Jellyfin server GUID. Scopes a sync binding to one server, so pointing the same account at a different server stops rather than silently writing to it.', max_length=255),
        ),
        AddFieldIfNotExists(
            model_name='plexaccount',
            name='mark_watched_checkpoint',
            field=models.DateTimeField(blank=True, help_text='Newest Plex history viewedAt already polled', null=True),
        ),
        AddFieldIfNotExists(
            model_name='plexaccount',
            name='mark_watched_sync_enabled',
            field=models.BooleanField(default=False, help_text='Whether recurring Plex history polling for manually marked watched items is enabled'),
        ),
        AddFieldIfNotExists(
            model_name='plexwatchlistsyncitem',
            name='source_server_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='collectionsourcestate',
            name='source',
            field=models.CharField(choices=[('plex', 'Plex'), ('jellyfin', 'Jellyfin'), ('radarr', 'Radarr'), ('sonarr', 'Sonarr'), ('mylar', 'Mylar3'), ('kapowarr', 'Kapowarr')], max_length=20),
        ),
        migrations.AlterField(
            model_name='collectionsourcestate',
            name='source_instance_id',
            field=models.PositiveIntegerField(blank=True, help_text='PK of the Radarr/Sonarr/Mylar/Kapowarr instance this row came from; unused for plex/jellyfin', null=True),
        ),
        AddIndexIfNotExists(
            model_name='plexwatchlistsyncitem',
            index=models.Index(fields=['user', 'source_server_id'], name='integration_user_id_e5fb7f_idx'),
        ),
        AddConstraintIfNotExists(
            model_name='importrun',
            constraint=models.UniqueConstraint(condition=models.Q(('source', 'trakt'), ('status', 'running'), models.Q(('phase', ''), _negated=True)), fields=('user', 'source'), name='one_active_durable_import'),
        ),
        AddConstraintIfNotExists(
            model_name='plexwatchlistsyncitem',
            constraint=models.UniqueConstraint(fields=('user', 'item', 'source_username', 'source_server_id'), name='integrations_plexwatchlistsyncitem_unique_user_item_server'),
        ),
        AddFieldIfNotExists(
            model_name='cataloggrant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_grants', to=settings.AUTH_USER_MODEL),
        ),
        AddFieldIfNotExists(
            model_name='embyaccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emby_account', to=settings.AUTH_USER_MODEL),
        ),
        AddFieldIfNotExists(
            model_name='externalreference',
            name='corrected_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrected_external_references', to='app.item'),
        ),
        AddFieldIfNotExists(
            model_name='externalreference',
            name='matched_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_external_references', to='app.item'),
        ),
        AddFieldIfNotExists(
            model_name='externalreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_references', to=settings.AUTH_USER_MODEL),
        ),
        AddFieldIfNotExists(
            model_name='importchunkreceipt',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunk_receipts', to='integrations.importrun'),
        ),
        AddFieldIfNotExists(
            model_name='importoverwritetarget',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overwrite_targets', to='integrations.importrun'),
        ),
        AddFieldIfNotExists(
            model_name='kapowarrinstance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kapowarr_instances', to=settings.AUTH_USER_MODEL),
        ),
        AddFieldIfNotExists(
            model_name='kavitaaccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kavita_account', to=settings.AUTH_USER_MODEL),
        ),
        AddFieldIfNotExists(
            model_name='kavitalink',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kavita_links', to='app.item'),
        ),
        AddFieldIfNotExists(
            model_name='kavitalink',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kavita_links', to=settings.AUTH_USER_MODEL),
        ),
        AddFieldIfNotExists(
            model_name='kodiaccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kodi_account', to=settings.AUTH_USER_MODEL),
        ),
        AddFieldIfNotExists(
            model_name='komgaaccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='komga_account', to=settings.AUTH_USER_MODEL),
        ),
        AddFieldIfNotExists(
            model_name='komgabooklink',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komga_book_links', to='app.item'),
        ),
        AddFieldIfNotExists(
            model_name='komgabooklink',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komga_book_links', to=settings.AUTH_USER_MODEL),
        ),
        AddFieldIfNotExists(
            model_name='mylarinstance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mylar_instances', to=settings.AUTH_USER_MODEL),
        ),
        AddFieldIfNotExists(
            model_name='oauthdeviceauthorization',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_authorizations', to='integrations.oauthclient'),
        ),
        AddFieldIfNotExists(
            model_name='oauthdeviceauthorization',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oauth_device_authorizations', to=settings.AUTH_USER_MODEL),
        ),
        AddFieldIfNotExists(
            model_name='oauthrefreshtoken',
            name='access_token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oauth_refresh_tokens', to='integrations.integrationtoken'),
        ),
        AddFieldIfNotExists(
            model_name='oauthrefreshtoken',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to='integrations.oauthclient'),
        ),
        AddFieldIfNotExists(
            model_name='oauthrefreshtoken',
            name='replaced_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaces', to='integrations.oauthrefreshtoken'),
        ),
        AddFieldIfNotExists(
            model_name='oauthrefreshtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_refresh_tokens', to=settings.AUTH_USER_MODEL),
        ),
        AddFieldIfNotExists(
            model_name='outboundstatedelivery',
            name='change',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='app.watchstatechange'),
        ),
        AddFieldIfNotExists(
            model_name='outboundstatedelivery',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_deliveries', to='app.item'),
        ),
        AddFieldIfNotExists(
            model_name='outboundstatedelivery',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_deliveries', to=settings.AUTH_USER_MODEL),
        ),
        AddFieldIfNotExists(
            model_name='preparedimportentry',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prepared_entries', to='integrations.importrun'),
        ),
        AddFieldIfNotExists(
            model_name='providerstateobservation',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_state_observations', to='app.item'),
        ),
        AddFieldIfNotExists(
            model_name='providerstateobservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_state_observations', to=settings.AUTH_USER_MODEL),
        ),
        AddFieldIfNotExists(
            model_name='remoteaddon',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remote_addons', to=settings.AUTH_USER_MODEL),
        ),
        AddFieldIfNotExists(
            model_name='stateconflict',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_conflicts', to='app.item'),
        ),
        AddFieldIfNotExists(
            model_name='stateconflict',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_conflicts', to=settings.AUTH_USER_MODEL),
        ),
        AddFieldIfNotExists(
            model_name='syncbinding',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_bindings', to=settings.AUTH_USER_MODEL),
        ),
        AddFieldIfNotExists(
            model_name='stateconflict',
            name='binding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='integrations.syncbinding'),
        ),
        AddFieldIfNotExists(
            model_name='providerstateobservation',
            name='binding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='integrations.syncbinding'),
        ),
        AddFieldIfNotExists(
            model_name='outboundstatedelivery',
            name='binding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='integrations.syncbinding'),
        ),
        AddFieldIfNotExists(
            model_name='integrationeventreceipt',
            name='binding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_receipts', to='integrations.syncbinding'),
        ),
        AddIndexIfNotExists(
            model_name='integrationeventreceipt',
            index=models.Index(fields=['created_at'], name='integration_created_52500b_idx'),
        ),
        AddConstraintIfNotExists(
            model_name='integrationeventreceipt',
            constraint=models.UniqueConstraint(condition=models.Q(('binding__isnull', True)), fields=('user', 'client_event_id'), name='unique_unbound_user_client_event_id'),
        ),
        AddConstraintIfNotExists(
            model_name='integrationeventreceipt',
            constraint=models.UniqueConstraint(condition=models.Q(('binding__isnull', False)), fields=('binding', 'client_event_id'), name='unique_binding_client_event_id'),
        ),
        AddFieldIfNotExists(
            model_name='synccheckpoint',
            name='binding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='integrations.syncbinding'),
        ),
        AddFieldIfNotExists(
            model_name='unresolvedexternalreference',
            name='binding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unresolved_references', to='integrations.syncbinding'),
        ),
        AddIndexIfNotExists(
            model_name='cataloggrant',
            index=models.Index(fields=['user', 'created_at'], name='integration_user_id_29946d_idx'),
        ),
        AddIndexIfNotExists(
            model_name='externalreference',
            index=models.Index(fields=['user', 'review_status'], name='integration_user_id_558d7e_idx'),
        ),
        AddIndexIfNotExists(
            model_name='externalreference',
            index=models.Index(fields=['user', 'integration', 'source_account'], name='integration_user_id_70a21a_idx'),
        ),
        AddIndexIfNotExists(
            model_name='externalreference',
            index=models.Index(fields=['matched_item', 'media_type'], name='integration_matched_8ca43c_idx'),
        ),
        AddConstraintIfNotExists(
            model_name='externalreference',
            constraint=models.UniqueConstraint(fields=('user', 'integration', 'source_account', 'external_namespace', 'external_identity', 'media_type'), name='unique_user_external_reference'),
        ),
        AddIndexIfNotExists(
            model_name='importchunkreceipt',
            index=models.Index(fields=['publication_pending', 'run'], name='integration_publica_26faf6_idx'),
        ),
        AddConstraintIfNotExists(
            model_name='importchunkreceipt',
            constraint=models.UniqueConstraint(fields=('run', 'phase', 'start'), name='import_chunk_run_start'),
        ),
        AddIndexIfNotExists(
            model_name='importoverwritetarget',
            index=models.Index(fields=['run', 'deleted', 'ordinal'], name='integration_run_id_89c56a_idx'),
        ),
        AddConstraintIfNotExists(
            model_name='importoverwritetarget',
            constraint=models.UniqueConstraint(fields=('run', 'model_label', 'original_pk'), name='import_overwrite_original'),
        ),
        AddConstraintIfNotExists(
            model_name='kapowarrinstance',
            constraint=models.UniqueConstraint(fields=('user', 'base_url'), name='integrations_kapowarrinstance_unique_user_base_url'),
        ),
        AddConstraintIfNotExists(
            model_name='kavitalink',
            constraint=models.UniqueConstraint(fields=('user', 'kavita_key'), name='integrations_kavitalink_unique_user_key'),
        ),
        AddConstraintIfNotExists(
            model_name='komgabooklink',
            constraint=models.UniqueConstraint(fields=('user', 'komga_book_id'), name='integrations_komgabooklink_unique_user_book'),
        ),
        AddConstraintIfNotExists(
            model_name='mylarinstance',
            constraint=models.UniqueConstraint(fields=('user', 'base_url'), name='integrations_mylarinstance_unique_user_base_url'),
        ),
        AddConstraintIfNotExists(
            model_name='preparedimportentry',
            constraint=models.UniqueConstraint(fields=('run', 'ordinal'), name='import_entry_run_ordinal'),
        ),
        AddConstraintIfNotExists(
            model_name='remoteaddon',
            constraint=models.UniqueConstraint(fields=('user', 'manifest_url'), name='unique_remote_addon_per_user'),
        ),
        AddIndexIfNotExists(
            model_name='syncbinding',
            index=models.Index(fields=['user', 'status'], name='integration_user_id_81fcdf_idx'),
        ),
        AddConstraintIfNotExists(
            model_name='syncbinding',
            constraint=models.UniqueConstraint(fields=('user', 'client_kind', 'instance_key', 'profile_key'), name='unique_sync_binding_identity'),
        ),
        AddIndexIfNotExists(
            model_name='stateconflict',
            index=models.Index(fields=['user', 'status'], name='integration_user_id_78311e_idx'),
        ),
        AddConstraintIfNotExists(
            model_name='stateconflict',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('user', 'item', 'binding', 'reason'), name='unique_open_state_conflict'),
        ),
        AddIndexIfNotExists(
            model_name='providerstateobservation',
            index=models.Index(fields=['binding', 'observed_at'], name='integration_binding_2c36f4_idx'),
        ),
        AddConstraintIfNotExists(
            model_name='providerstateobservation',
            constraint=models.UniqueConstraint(fields=('binding', 'item'), name='unique_provider_observation_per_item'),
        ),
        AddIndexIfNotExists(
            model_name='outboundstatedelivery',
            index=models.Index(fields=['status', 'next_attempt_at'], name='integration_status_882653_idx'),
        ),
        AddIndexIfNotExists(
            model_name='outboundstatedelivery',
            index=models.Index(fields=['binding', 'status'], name='integration_binding_d5ea89_idx'),
        ),
        AddConstraintIfNotExists(
            model_name='outboundstatedelivery',
            constraint=models.UniqueConstraint(fields=('binding', 'item', 'target_revision'), name='unique_delivery_per_revision'),
        ),
        AddConstraintIfNotExists(
            model_name='outboundstatedelivery',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'in_flight')), fields=('binding', 'item'), name='unique_inflight_delivery_per_item'),
        ),
        AddConstraintIfNotExists(
            model_name='synccheckpoint',
            constraint=models.UniqueConstraint(fields=('binding', 'resource', 'direction'), name='unique_sync_checkpoint_position'),
        ),
        AddConstraintIfNotExists(
            model_name='unresolvedexternalreference',
            constraint=models.UniqueConstraint(fields=('binding', 'namespace', 'value', 'reason_code'), name='unique_unresolved_external_reference'),
        ),
        migrations.RunPython(preserve_jellyfin_authorizations, migrations.RunPython.noop),
    ]
