# Generated by Django 5.2.17 on 2026-10-07 18:16

from django.db import migrations, models

from importlib import import_module

_constraint_operations = import_module("integrations.migrations.0030_radarrinstance_sonarrinstance_and_more")
AddFieldIfNotExists = _constraint_operations.AddFieldIfNotExists


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0014_customlist_include_notes'),
    ]

    operations = [
        AddFieldIfNotExists(
            model_name='customlist',
            name='tiers',
            field=models.JSONField(blank=True, default=list, help_text='Tier names and colours for the Tiers view; empty uses the defaults.'),
        ),
        AddFieldIfNotExists(
            model_name='customlistitem',
            name='tier',
            field=models.CharField(blank=True, default='', help_text='Id of the tier this item is placed in; blank means Unranked.', max_length=32),
        ),
        migrations.AlterField(
            model_name='customlist',
            name='source',
            field=models.CharField(choices=[('local', 'Local'), ('trakt', 'Trakt'), ('mdblist', 'MDBList'), ('wetrakr', 'WeTrakr')], default='local', max_length=20),
        ),
    ]
