# Generated by Django 5.2.16 on 2026-08-25 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0127_user_hardcover_api_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="ui_language",
            field=models.CharField(
                choices=[
                    ("auto", "Auto (browser language)"),
                    ("en", "English"),
                    ("es", "Español"),
                ],
                default="auto",
                help_text="Preferred UI display language",
                max_length=10,
            ),
        ),
    ]
