# Generated by Django 5.2.16 on 2026-08-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0127_user_hardcover_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='custom_logo_data',
            field=models.TextField(blank=True, default='', help_text='Normalized custom navigation logo'),
        ),
        migrations.AddField(
            model_name='user',
            name='custom_theme',
            field=models.JSONField(blank=True, default=dict, help_text='Validated custom application color palette'),
        ),
        migrations.AddField(
            model_name='user',
            name='detail_page_layouts',
            field=models.JSONField(blank=True, default=dict, help_text='Visible and ordered sections for each detail page family'),
        ),
        migrations.AddField(
            model_name='user',
            name='logo_text',
            field=models.CharField(default='Floppy', help_text='Short navigation wordmark', max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='logo_text_font',
            field=models.CharField(choices=[('display', 'Floppy display'), ('sans', 'Clean sans'), ('serif', 'Editorial serif'), ('mono', 'Technical mono')], default='display', help_text='Font family used by the navigation wordmark', max_length=12),
        ),
        migrations.AddField(
            model_name='user',
            name='logo_text_size',
            field=models.PositiveSmallIntegerField(choices=[(16, '16px'), (17, '17px'), (18, '18px'), (19, '19px'), (20, '20px'), (21, '21px'), (22, '22px'), (23, '23px'), (24, '24px'), (25, '25px'), (26, '26px'), (27, '27px'), (28, '28px'), (29, '29px'), (30, '30px'), (31, '31px'), (32, '32px'), (33, '33px'), (34, '34px'), (35, '35px'), (36, '36px'), (37, '37px'), (38, '38px'), (39, '39px'), (40, '40px')], default=23, help_text='Font size used by the navigation wordmark'),
        ),
        migrations.AddField(
            model_name='user',
            name='logo_text_spacing',
            field=models.SmallIntegerField(choices=[(-2, '-2px'), (-1, '-1px'), (0, '0px'), (1, '1px'), (2, '2px'), (3, '3px'), (4, '4px'), (5, '5px'), (6, '6px')], default=-1, help_text='Letter spacing used by the navigation wordmark'),
        ),
        migrations.AddField(
            model_name='user',
            name='logo_text_weight',
            field=models.PositiveSmallIntegerField(choices=[(400, 'Regular'), (500, 'Medium'), (600, 'Semibold'), (700, 'Bold'), (800, 'Extra bold'), (900, 'Black')], default=800, help_text='Font weight used by the navigation wordmark'),
        ),
        migrations.AlterField(
            model_name='user',
            name='logo_style',
            field=models.CharField(choices=[('colorful', 'Original color'), ('monochrome', 'Monochrome'), ('text', 'Text'), ('custom', 'Custom image'), ('hidden', 'Hidden')], default='colorful', help_text='Preferred Floppy logo style', max_length=12),
        ),
        migrations.AlterField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('system', 'System default'), ('light', 'Light'), ('dark', 'Dark'), ('catppuccin_mocha', 'Catppuccin Mocha'), ('dracula', 'Dracula'), ('nord', 'Nord'), ('gruvbox', 'Gruvbox'), ('oled', 'OLED'), ('glass', 'Glass cinema'), ('plex', 'Plex inspired'), ('projector', 'Projector'), ('video_store', 'Video store'), ('custom', 'Custom palette')], default='system', max_length=20),
        ),
    ]
