# Generated by Django 5.2.16 on 2026-08-28 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0128_user_appearance'),
        ('users', '0128_user_ui_language'),
    ]

    operations = [
    ]
