# Generated by Django 5.2.16 on 2026-08-31 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0128_user_ui_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="anime_metadata_source_default",
            field=models.CharField(
                choices=[
                    ("mal", "MyAnimeList"),
                    ("tmdb", "The Movie Database"),
                    ("tvdb", "TheTVDB"),
                ],
                default="tmdb",
                help_text="Default metadata provider for Anime details and search tabs.",
                max_length=20,
            ),
        ),
    ]
