# Generated by Django 5.2.16 on 2026-08-25 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0128_add_up_next_home_row_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='now_playing_open_episode',
            field=models.BooleanField(default=True, help_text='Open the playing episode instead of its season'),
        ),
        migrations.AddField(
            model_name='user',
            name='show_up_next_episode_code',
            field=models.BooleanField(default=True, help_text='Show the season and episode code in the Up Next row'),
        ),
    ]
