# Generated by Django 5.2.16 on 2026-08-24 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0131_user_logo_customization'),
        ('users', '0132_merge_theme_collection_home'),
    ]

    operations = [
    ]
