# Generated by Django 5.2.16 on 2026-08-24 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0128_home_screen_all_media'),
        ('users', '0133_merge_20260824_1924'),
    ]

    operations = [
    ]
