# Generated by Django 5.2.16 on 2026-08-25 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0132_user_logo_typography'),
        ('users', '0135_merge_series_person_preferences'),
    ]

    operations = [
    ]
