# Generated by Django 5.2.16 on 2026-08-25 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0128_add_history_home_row_type'),
        ('users', '0129_user_now_playing_open_episode_and_more'),
        ('users', '0136_merge_20260825_0827'),
    ]

    operations = [
    ]
