# Generated by Django 5.2.16 on 2026-08-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0014_customlist_include_notes'),
        ('users', '0137_merge_20260825_0917'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='homescreenrow',
            name='home_screen_row_row_type_valid',
        ),
        migrations.AlterField(
            model_name='homescreenrow',
            name='row_type',
            field=models.CharField(choices=[('library_query', 'Library Row'), ('custom_list', 'List / Smart List'), ('recently_unrated', 'Recently Played - Not Rated'), ('up_next', 'Up Next'), ('history', 'History')], default='library_query', max_length=32),
        ),
        migrations.AddConstraint(
            model_name='homescreenrow',
            constraint=models.CheckConstraint(condition=models.Q(('row_type__in', ['library_query', 'custom_list', 'recently_unrated', 'up_next', 'history'])), name='home_screen_row_row_type_valid'),
        ),
    ]
