# Generated by Django 5.2.16 on 2026-08-25 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0130_home_screen_companion_parity'),
        ('users', '0138_remove_homescreenrow_home_screen_row_row_type_valid_and_more'),
    ]

    operations = [
    ]
