# Generated by Django 5.2.16 on 2026-08-27 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0129_user_detail_availability_preferences'),
        ('users', '0146_move_public_reviews_to_detail_layouts'),
    ]

    operations = [
    ]
