# Generated by Django 5.2.16 on 2026-08-28 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0133_person_known_for_limit'),
        ('users', '0147_merge_20260827_1623'),
    ]

    operations = [
    ]
