# Generated by Django 5.2.16 on 2026-09-08 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0131_alter_user_ui_language'),
        ('users', '0148_merge_20260828_1509'),
    ]

    operations = [
    ]
