# Generated by Django 5.2.16 on 2026-09-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0149_merge_20260908_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='logo_style',
            field=models.CharField(choices=[('colorful', 'Original color'), ('monochrome', 'Monochrome'), ('text', 'Text'), ('custom', 'Custom image'), ('hidden', 'Hidden')], default='colorful', help_text='Preferred Floppy logo style', max_length=12),
        ),
    ]
