# Generated by Django 5.2.17 on 2026-10-07 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from importlib import import_module

_constraint_operations = import_module("integrations.migrations.0030_radarrinstance_sonarrinstance_and_more")
_index_operations = import_module("app.migrations.0134_item_app_item_media_lookup_idx")
AddFieldIfNotExists = _constraint_operations.AddFieldIfNotExists
AddConstraintIfNotExists = _constraint_operations.AddConstraintIfNotExists
RemoveConstraintIfExists = _constraint_operations.RemoveConstraintIfExists
AddIndexIfNotExists = _index_operations.AddIndexIfNotExists

CARD_TYPES = ("tv", "season", "episode", "movie", "anime", "manga", "game", "book", "comic", "comicissue", "boardgame", "music", "podcast", "video", "person")


def seed_card_preferences(apps, schema_editor):
    """Preserve saved card preferences before their old columns are removed."""
    user_model = apps.get_model("users", "User")
    manager = user_model.objects.using(schema_editor.connection.alias)
    pending = []
    for user in manager.all().iterator(chunk_size=500):
        if user.card_metadata:
            continue
        display = "always" if user.media_card_subtitle_display == "always" else "hover"
        line_display = "dormant" if display == "always" else "hover"
        profiles = {}
        for media_type in CARD_TYPES:
            fields = {
                "person": ["role"], "music": ["artist", "release_year"],
                "book": ["release_year", "series_position", "progress"], "episode": [],
            }.get(media_type, ["release_year", "progress"])
            if not user.progress_bar:
                fields = [field for field in fields if field != "progress"]
            profiles[media_type] = {
                "display": display, "fields": fields,
                "lines": [{"fields": [field], "display": line_display} for field in fields],
                "options": {
                    "rating": {"hide_zero": user.hide_zero_rating, "show": True},
                    "title": {"overflow": "ellipsis", "lines": 1, "hover": "bleed", "hover_lines": 3},
                },
            }
        user.card_metadata = {"version": 1, "types": profiles}
        pending.append(user)
        if len(pending) == 500:
            manager.bulk_update(pending, ["card_metadata"])
            pending = []
    if pending:
        manager.bulk_update(pending, ["card_metadata"])


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0182_episodeorder_episodeorderchange_historicalvideo_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('lists', '0015_customlist_tiers_customlistitem_tier_and_more'),
        ('users', '0151_branding_presentation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('tv', 'TV Show'), ('season', 'TV Season'), ('episode', 'Episode'), ('movie', 'Movie'), ('anime', 'Anime'), ('manga', 'Manga'), ('game', 'Game'), ('book', 'Book'), ('comic', 'Comic'), ('comicissue', 'Comic Issue'), ('boardgame', 'Board Game'), ('music', 'Music'), ('podcast', 'Podcast'), ('video', 'Video'), ('history', 'History')], max_length=16)),
                ('name', models.CharField(max_length=100)),
                ('query', models.TextField(blank=True, default='')),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['media_type', 'position', 'id'],
            },
        ),
        RemoveConstraintIfExists(
            model_name='homescreenrow',
            name='home_screen_row_media_type_valid',
        ),
        RemoveConstraintIfExists(
            model_name='user',
            name='media_card_subtitle_display_valid',
        ),
        RemoveConstraintIfExists(
            model_name='user',
            name='rating_scale_valid',
        ),
        RemoveConstraintIfExists(
            model_name='user',
            name='last_search_type_valid',
        ),
        RemoveConstraintIfExists(
            model_name='user',
            name='list_detail_sort_valid',
        ),
        RemoveConstraintIfExists(
            model_name='user',
            name='list_detail_layout_valid',
        ),
        AddFieldIfNotExists(
            model_name='user',
            name='card_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Per-media-type subtitle fields shown under a card title'),
        ),
        migrations.RunPython(seed_card_preferences, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='user',
            name='hide_zero_rating',
        ),
        migrations.RemoveField(
            model_name='user',
            name='media_card_subtitle_display',
        ),
        migrations.RemoveField(
            model_name='user',
            name='progress_bar',
        ),
        AddFieldIfNotExists(
            model_name='user',
            name='book_metadata_source_default',
            field=models.CharField(choices=[('hardcover', 'Hardcover'), ('openlibrary', 'Open Library'), ('googlebooks', 'Google Books')], default='hardcover', help_text='Default metadata provider for Book details and search tabs.', max_length=20),
        ),
        AddFieldIfNotExists(
            model_name='user',
            name='comic_metadata_source_default',
            field=models.CharField(choices=[('comicvine', 'Comic Vine'), ('gcd', 'Grand Comics Database')], default='comicvine', help_text='Default metadata provider for Comic details and search tabs.', max_length=20),
        ),
        AddFieldIfNotExists(
            model_name='user',
            name='playback_webhook_secret',
            field=models.TextField(blank=True, default='', help_text='Encrypted shared secret for the playback webhook. When set, each request carries an X-Floppy-Signature header holding the HMAC-SHA256 of the exact body sent.'),
        ),
        AddFieldIfNotExists(
            model_name='user',
            name='playback_webhook_url',
            field=models.URLField(blank=True, default='', help_text='Outgoing webhook POSTed the live playback state whenever it changes. Blank disables it, which is the default.', max_length=500),
        ),
        AddFieldIfNotExists(
            model_name='user',
            name='seerr_api_key',
            field=models.TextField(blank=True, default='', help_text='Encrypted Seerr API key'),
        ),
        AddFieldIfNotExists(
            model_name='user',
            name='seerr_url',
            field=models.URLField(blank=True, help_text='Seerr server URL, used to request movies and shows from Floppy'),
        ),
        AddFieldIfNotExists(
            model_name='user',
            name='seerr_user_id',
            field=models.PositiveIntegerField(blank=True, help_text='Seerr user id resolved from seerr_username when settings are saved', null=True),
        ),
        AddFieldIfNotExists(
            model_name='user',
            name='seerr_username',
            field=models.CharField(blank=True, default='', help_text='Seerr login (username or email) the requests are made as', max_length=255),
        ),
        AddFieldIfNotExists(
            model_name='user',
            name='show_discover',
            field=models.BooleanField(default=True, help_text='Show the Discover page and keep its caches warm'),
        ),
        AddFieldIfNotExists(
            model_name='user',
            name='show_recommendations',
            field=models.BooleanField(default=True, help_text='Show recommendations on media detail pages'),
        ),
        AddFieldIfNotExists(
            model_name='user',
            name='tv_auto_move_to_default_provider',
            field=models.BooleanField(default=True, help_text='Let the nightly job move TV shows tracked on the other provider to the default provider. Turned off when the user chooses to leave their library as it is after switching providers.'),
        ),
        AddFieldIfNotExists(
            model_name='user',
            name='video_direction',
            field=models.CharField(choices=[('asc', 'Ascending'), ('desc', 'Descending')], default='desc', max_length=4),
        ),
        AddFieldIfNotExists(
            model_name='user',
            name='video_enabled',
            field=models.BooleanField(default=True),
        ),
        AddFieldIfNotExists(
            model_name='user',
            name='video_layout',
            field=models.CharField(choices=[('grid', 'Grid'), ('table', 'Table')], default='grid', max_length=20),
        ),
        AddFieldIfNotExists(
            model_name='user',
            name='video_sort',
            field=models.CharField(choices=[('score', 'Rating'), ('critic_rating', 'Critic Rating'), ('title', 'Title'), ('author', 'Author'), ('popularity', 'Popularity'), ('progress', 'Progress'), ('runtime', 'Runtime'), ('time_to_beat', 'Time to Beat'), ('platform', 'Platform'), ('plays', 'Plays'), ('time_watched', 'Time Watched'), ('release_date', 'Release Date'), ('date_added', 'Date Added'), ('start_date', 'Start Date'), ('end_date', 'Last Watched'), ('next_episode_air_date', 'Episode Air Date'), ('time_left', 'Time Left')], default='title', max_length=32),
        ),
        AddFieldIfNotExists(
            model_name='user',
            name='video_status',
            field=models.CharField(choices=[('All', 'All'), ('Completed', 'Completed'), ('In progress', 'In Progress'), ('Planning', 'Planning'), ('Paused', 'Paused'), ('Dropped', 'Dropped')], default='All', max_length=128),
        ),
        migrations.AlterField(
            model_name='homescreenrow',
            name='media_type',
            field=models.CharField(choices=[('all', 'All media'), ('tv', 'TV Show'), ('season', 'TV Season'), ('episode', 'Episode'), ('movie', 'Movie'), ('anime', 'Anime'), ('manga', 'Manga'), ('game', 'Game'), ('book', 'Book'), ('comic', 'Comic'), ('comicissue', 'Comic Issue'), ('boardgame', 'Board Game'), ('music', 'Music'), ('podcast', 'Podcast'), ('video', 'Video')], max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_search_type',
            field=models.CharField(choices=[('tv', 'TV Show'), ('season', 'TV Season'), ('episode', 'Episode'), ('movie', 'Movie'), ('anime', 'Anime'), ('manga', 'Manga'), ('game', 'Game'), ('book', 'Book'), ('comic', 'Comic'), ('comicissue', 'Comic Issue'), ('boardgame', 'Board Game'), ('music', 'Music'), ('podcast', 'Podcast'), ('video', 'Video'), ('all', 'All')], default='tv', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='list_detail_layout',
            field=models.CharField(choices=[('grid', 'Grid'), ('table', 'Table'), ('tiers', 'Tiers')], default='grid', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='list_detail_sort',
            field=models.CharField(choices=[('date_added', 'Date Added'), ('custom', 'Custom'), ('title', 'Title'), ('media_type', 'Media Type'), ('rating', 'Rating'), ('progress', 'Progress'), ('status', 'Status'), ('release_date', 'Release Date'), ('start_date', 'Start Date'), ('end_date', 'End Date'), ('platform', 'Platform'), ('tier', 'Tier')], default='date_added', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='rating_scale',
            field=models.CharField(choices=[('10', '1-10 stars'), ('5', '1-5 stars'), ('0', 'Disabled')], default='10', help_text='Preferred rating scale for user scores', max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='ui_language',
            field=models.CharField(choices=[('auto', 'Auto (browser language)'), ('en', 'English'), ('de', 'Deutsch'), ('es', 'Español'), ('fr', 'Français')], default='auto', help_text='Preferred UI display language', max_length=10),
        ),
        AddConstraintIfNotExists(
            model_name='homescreenrow',
            constraint=models.CheckConstraint(condition=models.Q(('media_type__in', ['all', 'tv', 'season', 'movie', 'anime', 'manga', 'game', 'book', 'comic', 'comicissue', 'boardgame', 'music', 'podcast', 'video'])), name='home_screen_row_media_type_valid'),
        ),
        AddConstraintIfNotExists(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('last_search_type__in', ['tv', 'movie', 'anime', 'manga', 'game', 'book', 'comic', 'comicissue', 'boardgame', 'music', 'podcast', 'video', 'all'])), name='last_search_type_valid'),
        ),
        AddConstraintIfNotExists(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('book_metadata_source_default__in', ['hardcover', 'openlibrary', 'googlebooks'])), name='book_metadata_source_default_valid'),
        ),
        AddConstraintIfNotExists(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('comic_metadata_source_default__in', ['comicvine', 'gcd'])), name='comic_metadata_source_default_valid'),
        ),
        AddConstraintIfNotExists(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('list_detail_sort__in', ['date_added', 'custom', 'title', 'media_type', 'rating', 'progress', 'status', 'release_date', 'start_date', 'end_date', 'platform', 'tier'])), name='list_detail_sort_valid'),
        ),
        AddConstraintIfNotExists(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('list_detail_layout__in', ['grid', 'table', 'tiers'])), name='list_detail_layout_valid'),
        ),
        AddConstraintIfNotExists(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('video_layout__in', ['grid', 'table'])), name='video_layout_valid'),
        ),
        AddConstraintIfNotExists(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('video_sort__in', ['score', 'critic_rating', 'title', 'author', 'popularity', 'progress', 'runtime', 'time_to_beat', 'platform', 'plays', 'time_watched', 'release_date', 'date_added', 'start_date', 'end_date', 'next_episode_air_date', 'time_left'])), name='video_sort_valid'),
        ),
        AddConstraintIfNotExists(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('video_direction__in', ['asc', 'desc'])), name='video_direction_valid'),
        ),
        AddConstraintIfNotExists(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('rating_scale__in', ['10', '5', '0'])), name='rating_scale_valid'),
        ),
        AddFieldIfNotExists(
            model_name='savedview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_views', to=settings.AUTH_USER_MODEL),
        ),
        AddIndexIfNotExists(
            model_name='savedview',
            index=models.Index(fields=['user', 'media_type', 'position'], name='users_saved_user_id_2d992d_idx'),
        ),
    ]
