# Generated by Django 5.2.17 on 2026-10-07 18:16

from django.conf import settings
from django.db import migrations, models

from importlib import import_module

_constraint_operations = import_module("integrations.migrations.0030_radarrinstance_sonarrinstance_and_more")
AddFieldIfNotExists = _constraint_operations.AddFieldIfNotExists
AddConstraintIfNotExists = _constraint_operations.AddConstraintIfNotExists
RemoveConstraintIfExists = _constraint_operations.RemoveConstraintIfExists


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0182_episodeorder_episodeorderchange_historicalvideo_and_more'),
        ('events', '0014_delete_empty_content_number_comic_events'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        RemoveConstraintIfExists(
            model_name='event',
            name='unique_item_null_content_number',
        ),
        AddFieldIfNotExists(
            model_name='event',
            name='alert_failed_users',
            field=models.ManyToManyField(blank=True, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        AddFieldIfNotExists(
            model_name='event',
            name='region',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        AddFieldIfNotExists(
            model_name='event',
            name='release_type',
            field=models.CharField(blank=True, choices=[('digital', 'Digital'), ('physical', 'Physical')], default='', max_length=10),
        ),
        AddConstraintIfNotExists(
            model_name='event',
            constraint=models.UniqueConstraint(condition=models.Q(('content_number__isnull', True)), fields=('item', 'release_type', 'region'), name='unique_item_release_null_content_number'),
        ),
    ]
